branches:
  only:
    - master
language: php
php:
  - "5.3"
before_script:
  - host projects.bit3.de
  - dig projects.bit3.de
  - ping -c 3 projects.bit3.de
  - curl http://packages.bit3.de/packages.json
  - composer require --dev bit3/php-coding-standard:@dev
  - composer require --dev squizlabs/php_codesniffer:1.*
script: ant
